version: '3.1'


services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
        - "8883:8883"
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
    networks:
      - mynet
  
  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - mynet
  
  manager:
    image: emqx/ekuiper-manager:1.8.0
    container_name: manager
    ports:
      - "9082:9082"
    restart: unless-stopped
    volumes:
      - ./volumes/manager_data:/ekuiper-manager/data
    environment:
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081" 
    networks:
      - mynet
  
  ekuiper:
    image: lfedge/ekuiper:1.8.0
    ports:
      - "9081:9081"
    container_name: ekuiper
    hostname: ekuiper
    restart: unless-stopped
    user: root
    volumes:
      - ./volumes/ekuiper/data:/kuiper/data
      - ./volumes/ekuiper/log:/kuiper/log
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://broker.emqx.io:1883"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"
    networks:
      - mynet
  
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    networks:
      - mynet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    networks:
      - mynet
  
  server-microservice:
    image: server-microservice
    container_name: server-microservice
    networks:
      - mynet
    depends_on:
      - mosquitto

  filter-microservice:
    image: filter-microservice
    container_name: filter-microservice
    networks:
      - mynet
    depends_on:
      - mosquitto
      - nats

  dashboard-microservice:
    image: dashboard-microservice
    container_name: dashboard-microservice
    networks:
      - mynet
    depends_on:
      - nats
      - influxdb
      - grafana

  command-microservice:
    image: commandmicroservice
    container_name: command-microservice
    ports:
      - "5117:80"
    networks:
      - mynet
    depends_on:
      - mosquitto
      - ekuiper
      - manager

networks:
  mynet:
    driver: bridge