version: '3.1'


services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
        - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - mynet
  
  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - mynet


networks:
  mynet:
    driver: bridge